name: Java build with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [
            8,
            11,
            17
        ]
        os: [
          ubuntu-latest
        ]
      fail-fast: false

    name: Java ${{ matrix.java-version }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Compile
        run: ./gradlew assemble

      # this step is required for Java version 16 and up, because some internal classes used
      # for the spotless plugin are no longer accessible. This is the official workaround provided
      # on the google-java-format github page.
      # these settings will cause Java 8 to crash, so they are only applied to later versions.
      - name: Set up Gradle workaround for formatting and testing
        if: ${{ matrix.java-version >= 16 }}
        run: |
          echo 'org.gradle.jvmargs=\
                  --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
                  --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
                  --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
                  --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
                  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED' > gradle.properties

      - name: Test
        run: ./gradlew check
      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: jar (JDK ${{ matrix.java-version }})
          path: dynatrace/build/libs/*.jar
          if-no-files-found: error
      - name: Upload unit test results
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests-results (JDK ${{ matrix.java-version }})
          path: dynatrace/build/reports/tests/test/
